name: Integration tests (PR)
permissions:
  id-token: write
  contents: read
jobs:
  integration:
    name: Integration
    uses: ./.github/workflows/integration.yml
    with:
      environment: PR integration tests
      ref: ${{ github.event.pull_request.head.sha }}
env:
  GARALT_SECRET: ${{ secrets.GARALT }}
on:
  pull_request_target: null
